select
    observation_id,
    venue,
    entity_id as market_id,
    batch_id,
    page_id,
    endpoint,
    observed_at,
    b.batch_loaded_at,
    source_updated_at,
    payload_hash,
    source_kind,
    json_pointer,
    json_extract_string(normalized, '$.question') as question,
    json_extract_string(normalized, '$.slug') as slug,
    json_extract_string(normalized, '$.description') as description,
    json_extract_string(normalized, '$.condition_id') as condition_id,
    json_extract_string(normalized, '$.source_market_version') as source_market_version,
    json_extract_string(normalized, '$.protocol') as protocol,
    json_extract_string(normalized, '$.tick_size') as tick_size,
    json_extract_string(normalized, '$.minimum_order_size') as minimum_order_size,
    json_extract_string(normalized, '$.volume') as volume,
    json_extract_string(normalized, '$.liquidity') as liquidity,
    json_extract_string(normalized, '$.identity_error') as identity_error,
    json_extract_string(normalized, '$.membership_mode') as membership_mode,
    json_extract_string(normalized, '$.enclosing_event_id') as enclosing_event_id,
    json_extract_string(normalized, '$.semantic_hash') as semantic_hash,
    cast(json_extract_string(normalized, '$.active') as boolean) as active,
    cast(json_extract_string(normalized, '$.closed') as boolean) as closed,
    cast(json_extract_string(normalized, '$.archived') as boolean) as archived,
    cast(json_extract_string(normalized, '$.resolved') as boolean) as resolved,
    cast(json_extract_string(normalized, '$.neg_risk') as boolean) as neg_risk,
    cast(json_extract_string(normalized, '$.enable_order_book') as boolean) as enable_order_book,
    cast(json_extract_string(normalized, '$.accepting_orders') as boolean) as accepting_orders,
    cast(json_extract_string(normalized, '$.usable') as boolean) as usable,
    cast(json_extract_string(normalized, '$.tags_present') as boolean) as tags_present,
    cast(json_extract_string(normalized, '$.created_at') as timestamptz) as created_at,
    cast(json_extract_string(normalized, '$.start_at') as timestamptz) as start_at,
    cast(json_extract_string(normalized, '$.end_at') as timestamptz) as end_at,
    cast(json_extract_string(normalized, '$.close_at') as timestamptz) as close_at,
    cast(json_extract_string(normalized, '$.resolved_at') as timestamptz) as resolved_at,
    cast(json_extract_string(normalized, '$.end_at') as timestamptz) as end_date,
    json_extract(normalized, '$.outcomes') as outcomes_json,
    json_extract(normalized, '$.raw_outcomes') as raw_outcomes,
    json_extract(normalized, '$.raw_clob_token_ids') as raw_clob_token_ids,
    json_extract(normalized, '$.raw_position_ids') as raw_position_ids,
    json_extract(normalized, '$.tags') as tags_json,
    json_extract(normalized, '$.memberships') as event_refs_json
from {{ source('bronze', 'market_observations') }} o
join {{ ref('stg_gamma__batches') }} b using (batch_id)
