select
    observation_id,
    venue,
    entity_id as event_id,
    batch_id,
    page_id,
    endpoint,
    observed_at,
    b.batch_loaded_at,
    source_updated_at,
    payload_hash,
    json_extract_string(normalized, '$.title') as title,
    json_extract_string(normalized, '$.slug') as slug,
    json_extract_string(normalized, '$.ticker') as ticker,
    json_extract_string(normalized, '$.description') as description,
    json_extract_string(normalized, '$.volume') as volume,
    json_extract_string(normalized, '$.liquidity') as liquidity,
    json_extract_string(normalized, '$.open_interest') as open_interest,
    json_extract_string(normalized, '$.semantic_hash') as semantic_hash,
    cast(json_extract_string(normalized, '$.active') as boolean) as active,
    cast(json_extract_string(normalized, '$.closed') as boolean) as closed,
    cast(json_extract_string(normalized, '$.archived') as boolean) as archived,
    cast(json_extract_string(normalized, '$.neg_risk') as boolean) as neg_risk,
    cast(json_extract_string(normalized, '$.tags_present') as boolean) as tags_present,
    cast(json_extract_string(normalized, '$.series_present') as boolean) as series_present,
    cast(json_extract_string(normalized, '$.created_at') as timestamptz) as created_at,
    cast(json_extract_string(normalized, '$.start_date') as timestamptz) as start_date,
    cast(json_extract_string(normalized, '$.end_date') as timestamptz) as end_date,
    json_extract(normalized, '$.tags') as tags_json,
    json_extract(normalized, '$.series') as series_json
from {{ source('bronze', 'event_observations') }} o
join {{ ref('stg_gamma__batches') }} b using (batch_id)
